### ISSUE TITLE
`docker-compose up --build -d` fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by mswezey23** [paritytech/substrate-telemetry#135]
Dockerfile: `RUN apk update && apk add python g++ make openssh git bash pdftk`

Error `required by world[pdftk]`

**Comment by mswezey23** [comment]
I removed `pdftk` from the file and it builds & runs

**Comment by bitsrules** [comment]
@mswezey23 
I get the same error removed pdftk but it it still fails. 
```tsc: not found```
I suspect node is not installed?

My host OS is Ubuntu 18.10 

```
Successfully built 36a32817e719
Successfully tagged substrate-telemetry_telemetry-backend:latest
Starting substrate-telemetry_telemetry-frontend_1 ... done
Starting substrate-telemetry_telemetry-backend_1 ... done
Attaching to substrate-telemetry_telemetry-frontend_1, substrate-telemetry_telemetry-backend_1
telemetry-frontend_1 | yarn run v1.15.2
telemetry-frontend_1 | $ scripts/start-frontend.sh
telemetry-frontend_1 | scripts/build-common.sh: line 1: tsc: not found
telemetry-frontend_1 | npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1555919622016-0.9805029290782374/node but npm is using /usr/local/bin/node itself. Use the --scripts-prepend-node-path option to include the path for the node binary npm was executed with.
telemetry-frontend_1 |
telemetry-frontend_1 | > @dotstats/frontend@0.1.0 start /app/packages/frontend
telemetry-frontend_1 | > react-scripts-ts start
telemetry-frontend_1 |
telemetry-frontend_1 | sh: react-scripts-ts: not found
telemetry-frontend_1 | npm ERR! file sh
telemetry-frontend_1 | npm ERR! code ELIFECYCLE
telemetry-frontend_1 | npm ERR! errno ENOENT
telemetry-frontend_1 | npm ERR! syscall spawn
telemetry-frontend_1 | npm ERR! @dotstats/frontend@0.1.0 start: react-scripts-ts start
telemetry-frontend_1 | npm ERR! spawn ENOENT
telemetry-frontend_1 | npm ERR!
telemetry-frontend_1 | npm ERR! Failed at the @dotstats/frontend@0.1.0 start script.
telemetry-frontend_1 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
telemetry-frontend_1 | npm WARN Local package.json exists, but node_modules missing, did you mean to install?
telemetry-frontend_1 |
telemetry-frontend_1 | npm ERR! A complete log of this run can be found in:
telemetry-frontend_1 | npm ERR! /root/.npm/_logs/2019-04-22T07_53_42_374Z-debug.log
telemetry-frontend_1 | error Command failed with exit code 1.
telemetry-frontend_1 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
substrate-telemetry_telemetry-frontend_1 exited with code 1
telemetry-backend_1 | yarn run v1.15.2
telemetry-backend_1 | $ scripts/start-backend.sh
telemetry-backend_1 | scripts/build-common.sh: line 1: tsc: not found
telemetry-backend_1 | scripts/build-backend.sh: line 1: tsc: not found
telemetry-backend_1 | internal/modules/cjs/loader.js:670
telemetry-backend_1 | throw err;
telemetry-backend_1 | ^
telemetry-backend_1 |
telemetry-backend_1 | Error: Cannot find module '/app/packages/backend/build/index.js'
telemetry-backend_1 | at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
telemetry-backend_1 | at Function.Module._load (internal/modules/cjs/loader.js:591:27)
telemetry-backend_1 | at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
telemetry-backend_1 | at internal/main/run_main_module.js:21:11
telemetry-backend_1 | error Command failed with exit code 1.
telemetry-backend_1 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
substrate-telemetry_telemetry-backend_1 exited with code 1
```

**Comment by mswezey23** [comment]
@bitsrules 

I think node is installed on your system, but typescript isn't. 
What system are you on? Ubuntu or Mac?

Checkout this thread and see if that fixes it for you.
https://stackoverflow.com/questions/39404922/tsc-command-not-found-in-compiling-typescript

**Comment by bitsrules** [comment]
@mswezey23 My host system is Ubuntu 18.10, but the docker file uses node:alpine

I tweaked the Dockerfile a bit but now I think I have two new versions of typescript and some missing dependencies?

Dockerfile:
```
FROM node:alpine

WORKDIR /app

RUN apk add --update nodejs nodejs-npm
RUN apk update && apk add python g++ make openssh git bash
RUN export PYTHONPATH=${PYTHONPATH}:/usr/lib/python2.7
RUN npm i -g react-scripts-ts typescript
RUN echo 'export PATH=/usr/local/bin:$PATH' >>~/.bash_profile
RUN source ~/.bash_profile
RUN tsc --init
RUN npm install

COPY ./package.json yarn.lock ./

RUN yarn 

COPY . .

# Frontend is exposing 3000
# Backend is exposing 8080
# No need for expose, if using docker-compose & docker run -p 3000:3000
```

Output from running ``` docker-compose up --build ```
```
telemetry-backend_1   | 
telemetry-backend_1   | 54 http.createServer((request, response) => {
telemetry-backend_1   |                       ~~~~~~~
telemetry-backend_1   | 
telemetry-backend_1   | packages/backend/src/index.ts:54:29 - error TS7006: Parameter 'response' implicitly has an 'any' type.
telemetry-backend_1   | 
telemetry-backend_1   | 54 http.createServer((request, response) => {
telemetry-backend_1   |                                ~~~~~~~~
telemetry-backend_1   | 
telemetry-backend_1   | packages/backend/src/index.ts:64:51 - error TS2339: Property 'id' does not exist on type '{}'.
telemetry-backend_1   | 
telemetry-backend_1   | 64       const node = nodeList.filter((node) => node.id == nodeId)[0];
telemetry-backend_1   |                                                      ~~
telemetry-backend_1   | 
telemetry-backend_1   | packages/backend/src/index.ts:67:29 - error TS2339: Property 'networkState' does not exist on type '{}'.
telemetry-backend_1   | 
telemetry-backend_1   | 67         response.write(node.networkState);
telemetry-backend_1   |                                ~~~~~~~~~~~~
telemetry-backend_1   | 
telemetry-backend_1   | packages/backend/src/location.ts:2:30 - error TS2307: Cannot find module '@dotstats/common'.
telemetry-backend_1   | 
telemetry-backend_1   | 2 import { Maybe, Types } from '@dotstats/common';
telemetry-backend_1   |                                ~~~~~~~~~~~~~~~~~~
telemetry-backend_1   | 
telemetry-backend_1   | packages/backend/src/message.ts:1:22 - error TS2307: Cannot find module 'ws'.
telemetry-backend_1   | 
telemetry-backend_1   | 1 import { Data } from 'ws';
telemetry-backend_1   |                        ~~~~
telemetry-backend_1   | 
telemetry-backend_1   | packages/backend/src/message.ts:2:30 - error TS2307: Cannot find module '@dotstats/common'.
telemetry-backend_1   | 
telemetry-backend_1   | 2 import { Maybe, Types } from '@dotstats/common';
telemetry-backend_1   |                                ~~~~~~~~~~~~~~~~~~
telemetry-backend_1   | 
telemetry-backend_1   | 
telemetry-backend_1   | Found 34 errors.
telemetry-backend_1   | 
telemetry-backend_1   | internal/modules/cjs/loader.js:670
telemetry-backend_1   |     throw err;
telemetry-backend_1   |     ^
telemetry-backend_1   | 
telemetry-backend_1   | Error: Cannot find module 'ws'
telemetry-backend_1   |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
telemetry-backend_1   |     at Function.Module._load (internal/modules/cjs/loader.js:591:27)
telemetry-backend_1   |     at Module.require (internal/modules/cjs/loader.js:723:19)
telemetry-backend_1   |     at require (internal/modules/cjs/helpers.js:14:16)
telemetry-backend_1   |     at Object.<anonymous> (/app/packages/backend/build/index.js:5:19)
telemetry-backend_1   |     at Module._compile (internal/modules/cjs/loader.js:816:30)
telemetry-backend_1   |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
telemetry-backend_1   |     at Module.load (internal/modules/cjs/loader.js:685:32)
telemetry-backend_1   |     at Function.Module._load (internal/modules/cjs/loader.js:620:12)
telemetry-backend_1   |     at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
telemetry-backend_1   | error Command failed with exit code 1.
telemetry-backend_1   | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
substrate-telemetry_telemetry-backend_1 exited with code 1
telemetry-frontend_1  | no-unused-variable is deprecated. Since TypeScript 2.9. Please use the built-in compiler checks instead.
telemetry-frontend_1  | Failed to compile.
telemetry-frontend_1  | 
telemetry-frontend_1  | ./src/App.tsx
telemetry-frontend_1  | Module not found: Can't resolve '@dotstats/common' in '/app/packages/frontend/src
```

**Comment by bitsrules** [comment]
I can see there is an existing issue on this https://github.com/paritytech/substrate-telemetry/pull/29 which has been closed.

I tried to use https://github.com/chevdor/dotstats/tree/will-docker but it does not build.
```
>docker build -t chevdor/polkadot-telemetry:latest .
Sending build context to Docker daemon  3.403MB
Step 1/7 : FROM mhart/alpine-node:10
 ---> 79922872c7e8
Step 2/7 : MAINTAINER "chevdor@gmail.com"
 ---> Using cache
 ---> 48765a708c5a
Step 3/7 : WORKDIR /app
 ---> Using cache
 ---> cdd5b296a05d
Step 4/7 : COPY . .
 ---> Using cache
 ---> 3a8656b4df00
Step 5/7 : RUN yarn
 ---> Running in 95ce8b8fb02d
yarn install v1.15.2
error An unexpected error occurred: "/app/package.json: Unexpected string in JSON at position 753".
info If you think this is a bug, please open a bug report with the information provided in "/app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c yarn' returned a non-zero code: 1
```

**Comment by starit** [comment]
same error

**Comment by DeepInThought** [comment]
It seems gcj was yanked from gcc 8, which is required for pdftk to build properly.

[https://bugs.alpinelinux.org/issues/10136](https://bugs.alpinelinux.org/issues/10136)

**Comment by TriplEight** [comment]
@marbar3778 why do we need `pdftk` here in the first place?

**Comment by marbar3778** [comment]
you don't, you can remove it and everything will still work fine, I don't have time for the next couple of days to make a PR, so won't b able to remove it

**Comment by antoncoding** [comment]
I simply remove `pdftk` from Dockerfile and it's working properly now.

**Comment by chevdor** [comment]
FYI, there is some on going work regarding the docker stuff atm. 
The backend is now no longer in Typescript. Is it required to leave this issue open?
