### ISSUE TITLE
error end steiking

### ISSUE THREAD

**Issue by maksim1618** [paritytech/substrate-telemetry#449]
Uncaught error. Something went wrong with the query and rendering of this component. Please supply all the details below when logging an issue, it may help in tracing the cause.

Cannot read properties of undefined (reading 'unwrap')

TypeError: Cannot read properties of undefined (reading 'unwrap')
at https://cloudflare-ipfs.com/ipns/dotapps.io/main.1ed7d9d2.js:19:642334
at Object.Oi [as useMemo] (https://cloudflare-ipfs.com/ipns/dotapps.io/react.01.83e78759.js:2:320520)
at t.useMemo (https://cloudflare-ipfs.com/ipns/dotapps.io/react.01.83e78759.js:2:604491)
at MTa (https://cloudflare-ipfs.com/ipns/dotapps.io/main.1ed7d9d2.js:19:642299)
at ii (https://cloudflare-ipfs.com/ipns/dotapps.io/react.01.83e78759.js:2:315816)
at Ui (https://cloudflare-ipfs.com/ipns/dotapps.io/react.01.83e78759.js:2:325334)
at zi (https://cloudflare-ipfs.com/ipns/dotapps.io/react.01.83e78759.js:2:324668)
at Ws (https://cloudflare-ipfs.com/ipns/dotapps.io/react.01.83e78759.js:2:371140)
at _l (https://cloudflare-ipfs.com/ipns/dotapps.io/react.01.83e78759.js:2:355139)
at Pl (https://cloudflare-ipfs.com/ipns/dotapps.io/react.01.83e78759.js:2:355067)

**Comment by maksim1618** [comment]
Uncaught error. Something went wrong with the query and rendering of this component. Please supply all the details below when logging an issue, it may help in tracing the cause.

Cannot read properties of undefined (reading 'unwrap')

TypeError: Cannot read properties of undefined (reading 'unwrap')
at https://cloudflare-ipfs.com/ipns/dotapps.io/main.1ed7d9d2.js:19:642334
at Object.Oi [as useMemo] (https://cloudflare-ipfs.com/ipns/dotapps.io/react.01.83e78759.js:2:320520)
at t.useMemo (https://cloudflare-ipfs.com/ipns/dotapps.io/react.01.83e78759.js:2:604491)
at MTa (https://cloudflare-ipfs.com/ipns/dotapps.io/main.1ed7d9d2.js:19:642299)
at ii (https://cloudflare-ipfs.com/ipns/dotapps.io/react.01.83e78759.js:2:315816)
at Ui (https://cloudflare-ipfs.com/ipns/dotapps.io/react.01.83e78759.js:2:325334)
at zi (https://cloudflare-ipfs.com/ipns/dotapps.io/react.01.83e78759.js:2:324668)
at Ws (https://cloudflare-ipfs.com/ipns/dotapps.io/react.01.83e78759.js:2:371140)
at _l (https://cloudflare-ipfs.com/ipns/dotapps.io/react.01.83e78759.js:2:355139)
at Pl (https://cloudflare-ipfs.com/ipns/dotapps.io/react.01.83e78759.js:2:355067)

**Comment by maksim1618** [comment]
Waiting for authorization from the extension. Please open the installed extension and approve or reject access.

**Comment by jsdw** [comment]
I'm afraid that none of your links currently work, and it's not even clear to me that this has anything to do with Telemetry at the moment. In order that we can help get to the bottom of your issue, could you provide more of a description, screenshots and, if possible, a way to reproduce your issue?

**Comment by jsdw** [comment]
I suspect your error messages are compeltely unrelated to Telemetry, so I'll close this. Feel free to reopen if you can provide more detail and such.

**Comment by maksim1618** [comment]
https://web.telegram.org/z/#835446916

**Comment by maksim1618** [comment]
> Я подозреваю, что ваши сообщения об ошибках совершенно не связаны с телеметрией, поэтому я закрою это. Не стесняйтесь снова открывать, если вы можете предоставить более подробную информацию и тому подобное.

https://web.telegram.org/z/#835446916
