### ISSUE TITLE
error

### ISSUE THREAD

**Issue by maksim1618** [paritytech/substrate-telemetry#450]
Uncaught error. Something went wrong with the query and rendering of this component. Please supply all the details below when logging an issue, it may help in tracing the cause.

Cannot read properties of undefined (reading 'unwrap')

TypeError: Cannot read properties of undefined (reading 'unwrap')
at https://cloudflare-ipfs.com/ipns/dotapps.io/main.1ed7d9d2.js:19:642334
at Object.Oi [as useMemo] (https://cloudflare-ipfs.com/ipns/dotapps.io/react.01.83e78759.js:2:320520)
at t.useMemo (https://cloudflare-ipfs.com/ipns/dotapps.io/react.01.83e78759.js:2:604491)
at MTa (https://cloudflare-ipfs.com/ipns/dotapps.io/main.1ed7d9d2.js:19:642299)
at ii (https://cloudflare-ipfs.com/ipns/dotapps.io/react.01.83e78759.js:2:315816)
at Ui (https://cloudflare-ipfs.com/ipns/dotapps.io/react.01.83e78759.js:2:325334)
at zi (https://cloudflare-ipfs.com/ipns/dotapps.io/react.01.83e78759.js:2:324668)
at Ws (https://cloudflare-ipfs.com/ipns/dotapps.io/react.01.83e78759.js:2:371140)
at _l (https://cloudflare-ipfs.com/ipns/dotapps.io/react.01.83e78759.js:2:355139)
at Pl (https://cloudflare-ipfs.com/ipns/dotapps.io/react.01.83e78759.js:2:355067)

https://web.telegram.org/z/#835446916

**Comment by jsdw** [comment]
Please stop pasting these errors here. If you'd like help with something you'll need to provide more detail.
