### ISSUE TITLE
Uncaught Error: Non-base58 character

### ISSUE THREAD

**Issue by ioannist** [paritytech/substrate-telemetry#527]
We have deployed a private telemetry and getting the following error when trying to load the Polkadex page. All other pages/networks work.

```
Uncaught Error: Non-base58 character
    at Object.decode (index.js:115:1)
    at e.default (decode.js:28:1)
    at PolkadotIcon.tsx:139:17
    at I (PolkadotIcon.tsx:148:14)
    at PolkadotIcon.tsx:177:18
    at h (PolkadotIcon.tsx:214:5)
    at e.a.render (PolkadotIcon.tsx:239:5)
    at Jo (react-dom.production.min.js:187:125)
    at Ho (react-dom.production.min.js:186:166)
    at Ra (react-dom.production.min.js:269:357)
```

**Comment by jsdw** [comment]
Are you using the most uptodate version of telemetry? My belief is that this issue was fixed a while ago in a slightly more recent version :)

**Comment by ioannist** [comment]
Latest release was on 2021-05-21 which is the one I am using

**Comment by niklasad1** [comment]
The latest release is: https://github.com/paritytech/substrate-telemetry/releases/tag/v12.0-b25f3fb

**Comment by jsdw** [comment]
Ah I see the confusion; we had 1 release from ages ago and didn't keep up with adding releases to that tab. I deleted the release there so that it's more obvious to look at the tags instead for now (until such a time as we use that Releases page properly for this)
